#!/usr/bin/env bash
# Configuring an Ubuntu server

# Backup the existing /etc/hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Add the new localhost and facebook.com mappings
sudo echo "127.0.0.2 localhost" >> /etc/hosts
sudo echo "8.8.8.8 facebook.com" >> /etc/hosts

# Restart the Docker daemon to pick up the changes
sudo service docker restart
